import { NextIntlClientProvider } from 'next-intl';
import QueryProvider from '@/providers/query';
import '../../styles/global.scss';
import locale_config from '@/config/locale';

type TRootLayoutProps = {
    children: React.ReactNode;
    params: {
        locale: string;
    };
};

export const metadata = {
    title: 'Next Starter Kit',
    description: 'Generated by create next app',
};

export function generateStaticParams() {
    const locales_params: {locale: typeof locale_config.locales[number]}[] = [];
    locale_config.locales.forEach((locale) => {
        locales_params.push({locale});
    });

    return locales_params;
}

const RootLayout = async ({children, params: {locale}}: TRootLayoutProps) => {
    const messages = (await import(`../../public/messages/${locale}.json`)).default;

    return (
        <html lang={locale}>
            <body>
                <QueryProvider>
                    <NextIntlClientProvider
                        locale={locale}
                        messages={messages}
                    >
                        {children}
                    </NextIntlClientProvider>
                </QueryProvider>
            </body>
        </html>
    );
};

export default RootLayout;
